### ISSUE TITLE
Add Tag Feature for Displaying Field Entries alongside Part/Inventory in Trees

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#445] opened 2021-08-28 03:05 UTC
Please add the ability to select fields to have their contents displayed alongside Parts and Inventory Items as they appear in the Part/Assembly/Inventory Trees.
The requirement begins with needing to see a Configuration value displayed with the associated Assembly Part as well as the any Build using that Assembly Template and the eventual Inventory Item that fills that part in the Build.  
Please explore the feasibility and challenges of generalizing beyond this requirement.

**Comment by joannekoch** [comment] 2021-11-23 13:28
I like the design of this new feature! The usage is clear and it is easy to add a tag. The selection of tag colors is a nice feature.

There is an issue that I discovered while testing.  When a tag is added and a value associated with a Configuration Name is dynamically inserted using "{}" curly braces, the Assembly part can no longer be found in the NavTree or in a Search of Assembly and Inventory.
![Capture](https://user-images.githubusercontent.com/65416034/143030921-f6c0acb0-e82e-4f12-b37d-98c49db1448b.PNG)

Selecting the carat on "Revision B" does not open the Sub Assemblies in the  Assemblies NavTree. The same thing occurs in the Inventory NavTree.
![Capture1](https://user-images.githubusercontent.com/65416034/143031697-300a1fe7-859c-4d61-a8a6-69098a3db191.PNG)

Searching for all Assemblies, does not return the Sub Assemblies for Singer.

![Capture2](https://user-images.githubusercontent.com/65416034/143031795-26e7ff8a-e444-4027-9eb3-092801c47de2.PNG)

**Comment by sbatchelder** [comment] 2021-11-29 21:52
I just merged the current release-1.7.0 and did a fresh wipe of the database (circa March 2021) and I do not experience these issues. 
Re Assembly Template search, it's not designed to return Assembly Parts / Sub-assemblies.


**Inventory NavTree with filter:**
![image](https://user-images.githubusercontent.com/44208509/143947515-239cbc52-d040-4d78-bba3-82e40c2ea669.png)



**Assembly NavTree with revision dropdown:**
![image](https://user-images.githubusercontent.com/44208509/143947734-a4556172-df52-48da-bda4-bc651f496b2d.png)



**Assembly Search:**
![image](https://user-images.githubusercontent.com/44208509/143947856-38213c0b-7f44-429d-9e7e-7460350981fb.png)

**Comment by joannekoch** [comment] 2021-11-29 23:24
How did you add the tags? When I specify a dynamic tag value, using {2} for example, the tag doesn't get added and it doesn't show up on the navtree. If I don't specify a value in the curly braces, the tag is added without issue as you showed above.

**Comment by sbatchelder** [comment] 2021-11-30 03:09
Ahh I see what the issue is now, okay. I'm adding some custom form field validating, so this should no longer be possible.

I also fixed the issue with the assembly part tabs not rendering right when clicked 👍

**Comment by joannekoch** [comment] 2021-12-07 13:54
Hey @sbatchelder , now I get a spinning wheel and a Server Error when I specify {12} in the Text field.

![Capture](https://user-images.githubusercontent.com/65416034/145041480-29482a90-6aa2-4223-a794-a25785105ef2.PNG)
}

**Comment by sbatchelder** [comment] 2021-12-07 23:57
@joannekoch 
I just submitted a fix to release-1.7.0
it was a particular sequence (with both `{}` and `config` was selected but `{}` is not-empty) that I had apparently missed. Thanks for finding it!!
-Sidney

**Comment by joannekoch** [comment] 2021-12-08 13:56
Hi Sidney,

Thanks for fixing it!

Joanne

**Comment by cahearn** [comment] 2021-12-15 19:45
Looking great!  Eventually it would be good to be able to edit the tags from the "Tag" tab, not just delete them.

One issue I found - there's inconsistencies in responses to clicking the "Add Tag" button.  I occasionally have to click multiple times before I get a response.  Also, I intermittent error messages like the one below.  Simply clicking again usually leads to a successful entry, but I can't reliably reproduce the errors.

![image](https://user-images.githubusercontent.com/14059724/146253919-24d9fc6e-8a25-43e0-a884-950f5e33ef90.png)

**Comment by joannekoch** [comment] 2022-05-09 19:09
The ONLY way I could reproduce the error Connor found above was to:

1. Select the Nominal Depth on the add tag screen.
2. Do NOT hit "Add Tag".
3. Open a new browser window and delete the Nominal Depth configuration from the associated Part.
4. Go to back to the Add Tag window and do NOT hit refresh.
5. The "Select a valid choice. That choice is not one of the available choices" error is presented.

Of course the Operator scenario above is NOT a valid one and the browser window in step 4 should have been refreshed showing that Nominal Depth is no longer a choice in the pull down. 

I recommend we resolved this issue and assume it was some sort of update/screen refresh error.

@sbatchelder, please let me know if you agree.

**Comment by sbatchelder** [comment] 2022-05-09 22:54
That seems to be the case for me too, and given the steps you described Joanne, it (a) makes sense that the error shows up and (b) is outside of the normal use-case scope. 

I think it's probably fine to close out this enhancement, and if @cahearn or a user sees this again we can open up a new bug issue.

**Comment by joannekoch** [comment] 2022-05-10 12:39
Thanks Sidney!  I will move this to Reviewer Approved so you can close it.

**Closed** 2022-06-15 19:50 UTC
Labels: enhancement
