### ISSUE TITLE
Search for Constants Event Date yields Django core error & Reviewer & Event Date yields no results

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#212] opened 2020-10-19 13:55 UTC
1.	Search on event date yields Django core error. 
<img width="700" alt="Search 1" src="https://user-images.githubusercontent.com/65416034/96459066-abac8c00-11ef-11eb-90f5-084a7f22d949.PNG">
<img width="735" alt="Search 2" src="https://user-images.githubusercontent.com/65416034/96459080-b109d680-11ef-11eb-8db3-c11b13f8ad6e.PNG">
2.	Search for reviewers yields no results. 
<img width="1111" alt="Search 3" src="https://user-images.githubusercontent.com/65416034/96459183-d1d22c00-11ef-11eb-81cf-0adcc85798b9.PNG">
<img width="714" alt="Search 4" src="https://user-images.githubusercontent.com/65416034/96459197-d72f7680-11ef-11eb-8113-ec20b71945f6.PNG">
3.     Search for date entered yields no results.
<img width="786" alt="Search 5" src="https://user-images.githubusercontent.com/65416034/96459306-fcbc8000-11ef-11eb-8832-3e6576dfd92c.PNG">
<img width="793" alt="Search 6" src="https://user-images.githubusercontent.com/65416034/96460096-da773200-11f0-11eb-9505-077771219253.PNG">

**Comment by sbatchelder** [comment] 2020-10-19 23:48
1. This error was caused by a typo in the backend. I can submit this fix for 1.6.0
2. Does username "admin" have a Name associated with it? The search keys-in on user.name, not user.username. 
3. This one is tricky. Date Entered aka created_at is stored as a datetime, so an "exact" match has to match YYYY:MM:DD hh:mm:ss. It's silly to expect this of users ofc and I'll fix it. 

2 and 3 can addressed with the new interface i'm working on for 1.6.1

**Comment by joannekoch** [comment] 2020-10-20 13:17
Username "admin" does not have a Name associated with it.  Admin is created automatically by Django. Ethan would know more about it.

**Comment by sbatchelder** [comment] 2020-10-21 20:17
(1) has been addressed in PR #218 for 1.6.0

(2) and (3) were moved to their own Issues, #219 and #220 and to milestone 1.6.1

As such this Issue divests itself from (2) and (3) and can be closed once Review for (1) is resolved.

**Comment by spetillo** [comment] 2020-10-27 15:45
Not for testing: PR #218 has been merged, so we just need to test that (1) above is resolved when we do testing on this ticket.

**Comment by cahearn** [comment] 2020-11-23 18:44
The error described in (1) above has been fixed in testing on Staging.  Good to go!

**Closed** 2021-02-02 15:24 UTC
Labels: bug
