### ISSUE TITLE
Bulk Export Deployment File Blank for Bulk Uploaded Github Deployment CSV

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#559] opened 2022-05-11 13:53 UTC
Uploaded the following Github Deployment CSV:
![Capture1](https://user-images.githubusercontent.com/65416034/167863905-698fed38-528e-49fe-8ffb-f293f6a6471a.PNG)

Exported Deployments using Bulk Download Tool->Export Deployments. Export resulted in the following files:

GS_Surface_Mooring__Deploy.csv - this build was uploaded. The build contents of this file is blank.
![Capture](https://user-images.githubusercontent.com/65416034/167864848-7b9ce611-328d-4ac2-beb6-90d49e1cd67f.PNG)

Salty_Reef_Deploy.csv - this build was created by hand. The build contents of this file are correct.
![Capture1](https://user-images.githubusercontent.com/65416034/167865026-1a4f5d2a-461b-416f-b379-cd99576f6704.PNG)

Build Screen Shot:

![Capture](https://user-images.githubusercontent.com/65416034/167865716-2036b9b4-32d6-4e1c-ab11-409d608d3a63.PNG)

**Comment by sbatchelder** [comment] 2022-06-08 22:27
Hi @joannekoch,

I'm trying to reproduce this but I'm having trouble. I can't seem to upload a valid CSV for deployments, I get a "Unable to parse Mooring UID or Deployment Number from Mooring UID" error.

Do you think we could do a zoom about it?

**Comment by sbatchelder** [comment] 2022-06-09 13:27
Thanks for the instructions! I'll try it out myself, but I'm going to close this Issue since it seems to be working properly now. Thanks!

**Closed by sbatchelder** 2022-06-09 13:27 UTC
Labels: bug
