### ISSUE TITLE
Inventory Build Search doesn't return Build information

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#400] opened 2021-05-24 17:31 UTC
If there are two builds (GS Surface Mooring - GS01SUMO-20002 & Singer - 000-654-987-20001) as shown in the screen below.

![Capture](https://user-images.githubusercontent.com/65416034/119383258-1abff680-bc91-11eb-9632-77f02049a911.PNG)

"Search->Inventory AND Build Contains 000-654-987-20001" returns nothing for build Singer - 000-654-987-20001. The search for the Build Number fails and only returns Inventory items if you search on Singer, the Assembly Template name.
![Capture](https://user-images.githubusercontent.com/65416034/119385101-ab97d180-bc93-11eb-90d4-5369807c599f.PNG)

![Capture](https://user-images.githubusercontent.com/65416034/119385178-c702dc80-bc93-11eb-8ad5-73fa12ae611d.PNG)

"Search->Inventory AND Build Contains GS Surface Mooring" returns nothing. Inconsistent results.
![Capture](https://user-images.githubusercontent.com/65416034/119385364-05989700-bc94-11eb-9cb9-9deac4de3ce1.PNG)

This is misleading to the user. It is not clear if this search is looking for the Build Number.
Tested on v1.7.0

**Comment by joannekoch** [comment] 2021-05-26 13:33
Perfect to clarify and add Build Name and Build Number to search options.  Thank you.

Build Name is working great, but Build Number search results in:

![image](https://user-images.githubusercontent.com/65416034/119668596-51b71900-be05-11eb-98e4-99aefad358ad.png)

**Comment by sbatchelder** [comment] 2021-05-26 19:15
this was caused by an errant typo (`"build_number "` with a space). 
I put in a fix but it's so minor it can wait until a some larger updates before being merged and folded in.
Thanks for catching this!!

**Comment by joannekoch** [comment] 2021-07-07 14:07
Fixed. Thank you!

**Closed** 2022-06-15 19:52 UTC
Labels: bug
